Stay Sphere Hotel Rails and Ruby Final Capstone  👨‍💻 👨‍💻 👨‍💻
tsheporamantso/final-capstone-react-front-end pull request #21
Opened 2024-03-06 10:08 UTC by tsheporamantso

## Stay Sphere Hotel Rails and Ruby Final Capstone  👨‍💻 👨‍💻 👨‍💻 
### On this milestone 🗿  we managed to implement the following
1. The user logs in to the website, only by typing the username (a proper authenticated login is a requirement if your group is made of 5 people).
2. In the navigation panel, the user can see links to:
   - Motorcycles/doctors/classes/items that you selected as a theme.
   - "Reserve" form.
   - "My reservations".
   - "Add motorcycle/doctor/class/item that you selected as a theme" (the link is visible to everybody).
   - "Delete motorcycle/doctor/class/item that you selected as a theme" (the link is visible to everybody).
3. On the main page, the user can see a [list of motorcycles/doctors/classes/items that you selected as a theme](https://www.behance.net/gallery/26425031/Vespa-Responsive-Redesign/modules/173005577).

4. When the user selects a specific item, they can see the [details page](https://www.behance.net/gallery/26425031/Vespa-Responsive-Redesign/modules/173005579) with its full description (skip the "Rotate image" button).

   - In the details page, the user can click the "Reserve" button (in the design you can see the "Configure" button - please replace it with the "Reserve" button).

5. When the user clicks the "Add item" link in the navigation panel they can see a form for adding a new item.

6. Make the app responsive, creating both mobile and desktop versions.

##### Additional features - Required for teams with 3-4 & 5 members (optional for others)

7. When the user clicks the "Delete item" link in the navigation panel they can see a list of all items with title and "Delete" button.
   - When the user clicks the "Delete" button, the selected item is marked as removed and does not show on the main list anymore.

- To reserve an appointment, the user has to select a date and city (username and selected item are autofilled).
  - Use the design based on the ["Book a vespa test-ride"](https://www.behance.net/gallery/26425031/Vespa-Responsive-Redesign/modules/173005583) and add all necessary inputs.
  - The user can also access the "Reserve" page from the navigation panel. In that case only username is autofilled.

8. When the user clicks the "My reservations" link in the navigation panel they can see a list of their reservations (with information about item name, date and city).
9. Add full documentation for your API.
10. Check and Correct Stylelint errors
11. Followed correct Gitflow

2024-03-06 17:07 UTC, vichuge reviewed
Hi dear student, 

Good job so far!
You still need to work on some issues to prepare your project for the final evaluation, but you are almost there!

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)


## Suggested changes
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2024-03-06 17:07 UTC, vichuge commented on src/App.js
> +function App() {
- Please, consider using arrow funcs according to Javascript ES6 good practices.

2024-03-06 17:07 UTC, vichuge commented on src/Components/AddPlace.js
> +function AddPlace() {
- Please, consider using arrow funcs according to Javascript ES6 good practices.

2024-03-06 17:07 UTC, vichuge commented on src/Components/AddReservation.js
> +function AddReservation() {
- Please, consider using arrow funcs according to Javascript ES6 good practices.

2024-03-06 17:07 UTC, vichuge commented on src/Components/DetailsPage.js
> +function DetailsPage() {
- Please, consider using arrow funcs according to Javascript ES6 good practices.

2024-03-06 17:07 UTC, vichuge commented on src/Components/Layout.js
> +function Layout() {
- Please, consider using arrow funcs according to Javascript ES6 good practices.

2024-03-06 17:07 UTC, vichuge commented on src/Components/MyReservations.js
> +function MyReservations() {
- Please, consider using arrow funcs according to Javascript ES6 good practices.

2024-03-06 17:07 UTC, vichuge commented on src/Components/Navigation.js
> +function Navigation() {
- Please, consider using arrow funcs according to Javascript ES6 good practices.

2024-03-06 17:07 UTC, vichuge commented on src/Components/PlaceList.js
> +function PlacesList() {
- Please, consider using arrow funcs according to Javascript ES6 good practices.

2024-03-06 17:07 UTC, vichuge commented on src/Components/UserAuth.js
> +function UserAuth({ setLoggedIn }) {
- Please, consider using arrow funcs according to Javascript ES6 good practices.

2024-03-06 17:07 UTC, vichuge commented on src/Components/UserSignUp.js
> +function UserSignUp() {
- Please, consider using arrow funcs according to Javascript ES6 good practices.

2024-03-06 17:07 UTC, vichuge commented on src/Components/AddPlace.js
> +      await axios.post(`http://localhost:3000/api/v1/users/${userId}/places`, placeData);
- It looks like this is an action. The actions are part of redux architecture, I kindly invite you to add all actions inside the redux folder, preferably with all actions together in place to add in the components

- Please, consider the same for other components with the same issue 😄

2024-03-07 11:16 UTC, Meltrust requested changes
Hi,

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation, but you are almost there!






### To highlight:

-  Actions have been moved to the redux folder✔️
-  Functions are now ES6 ✔️ 
-  Nice code organization ✔️ 
-  Good readme ✔️ 
-  Nice frontend ✔️ 



#### You are really close to finishing the Microverse program!! Keep it up! 👍👍👍

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

### After implementing the requested changes, please submit another review request. ♻️
_Check the comments under the review._







Cheers and Happy coding!👏👏👏

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the previous reviews unless it is requested otherwise._**

------

2024-03-07 11:16 UTC, Meltrust commented on src/Components/DeletePlace.js
> +const DeletePlace = () => {
- [ ] When I reserve a hotel:

![image](https://github.com/tsheporamantso/final-capstone-react-front-end/assets/57421823/ed6439b0-04bc-45ba-806a-ebe94041fa6f)

And then I try to delete it:

![image](https://github.com/tsheporamantso/final-capstone-react-front-end/assets/57421823/b629f6dd-a9cf-45b9-80e7-5a0b1c3ecec3)

This error will happen:

![image](https://github.com/tsheporamantso/final-capstone-react-front-end/assets/57421823/f491ae10-60e1-4721-bb36-d7fce6e2b82d)

![image](https://github.com/tsheporamantso/final-capstone-react-front-end/assets/57421823/a663defe-187b-41c8-b07d-245c39874aff)

![image](https://github.com/tsheporamantso/final-capstone-react-front-end/assets/57421823/7ef8eca3-2cc8-48c3-8f6d-96331df68b11)

The error will stay there and won't let me delete any other hotel unless I reload the page.

## Explanation

This is because the hotel is still reserved, so the server refuses to delete it.

## Solution and extra help

You could either:

- Include a message explaining that the hotel was not deleted and that the user should delete the reservation first.

OR

- In the server, in models/place.rb edit line 3 like this:

```ruby
  has_many :reservations, dependent: :destroy
```

Kindly notice the "dependent: :destroy" argument.  This will destroy all the existing reservations for you if the place gets deleted and the error will go away (tested).

Result:

Dev tools ok:

![image](https://github.com/tsheporamantso/final-capstone-react-front-end/assets/57421823/13f35d5c-c3a2-461d-9f8f-c48137f8dcf6)

The console ok:

![image](https://github.com/tsheporamantso/final-capstone-react-front-end/assets/57421823/c6ae3855-3896-4b19-aa3b-5ddc5553cdbd)

The reservation is gone correctly along with the hotel, and the error message is gone too:

![image](https://github.com/tsheporamantso/final-capstone-react-front-end/assets/57421823/d7fbfb3d-d21b-495c-a382-a861276f12f0)

Either way, now that you have the solution, kindly implement any option so your users won't get the error message, the delete function of your app will be a lot more usable, and your app will be perfect. 👍

2024-03-07 11:39 UTC, tsheporamantso commented on src/Components/DeletePlace.js
> +const DeletePlace = () => {
Hi @Meltrust 
<img src="https://media4.giphy.com/media/rHR8qP1mC5V3G/giphy.gif"/>
From the team we would like to thank you for the in-depth review and coaching, it is highly appreciated. 🤝

2024-03-07 11:54 UTC, Meltrust approved these changes
# **Wow, you did it 🎉**
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for the changes implemented 💪 🥇 ㊗️ 
#### _Unless you want to add more features, go ahead to your final presentation ⏩ ⏩ ⏩_ 
## You are about to finish the Microverse program.  You have come a long way!!!




### Good luck in the software industry!!  I'll see you there. ✨
### **Congratulations!!!!!!**  🎉
![applause](https://media.giphy.com/media/srg19CG0cKMuI/giphy.gif)

### To highlight

- Removing a hotel that has been reserved now deletes the reservation instead of displaying an error ✔️ 
- Superb job ✔️  



Cheers and Happy coding!👏👏👏


------

2024-03-07 12:19 UTC, merged